Allow changing max_uri_handlers for http Server
esp-rs/esp-idf-svc pull request #120
Opened 2022-08-09 05:58 UTC by usbalbin

2022-08-10 13:23 UTC, MabezDev requested changes
LGTM, could you run rustfmt to fix the CI errors?

2022-08-11 05:05 UTC, usbalbin commented
Sure, done

2022-08-17 11:16 UTC, MabezDev approved these changes
Perfect, thank you!

2022-08-17 11:16 UTC, merged

2022-08-17 15:26 UTC, usbalbin commented
Thank you :)