Fix #146 by providing std::ptr::null if payload is empty
esp-rs/esp-idf-svc pull request #147
Opened 2022-10-11 18:13 UTC by mike1703

this is fixing the issue that a pointer to [] is actually 0x1 (not 0x0).

I fixed not only publish() but also enqueue() as this was also not working (but failed silent for me).

There is a new commit https://github.com/espressif/esp-idf/issues/9719 which fixes the enqueue() function in esp-idf which would cause an actual issue in the rust enqueue() function as well.

2022-10-16 20:12 UTC, ivmarkov requested changes

2022-10-16 20:12 UTC, ivmarkov commented on src/mqtt/client.rs
> +            0 => std::ptr::null(),
Use core, not std.

2022-10-16 20:12 UTC, ivmarkov commented on src/mqtt/client.rs
> +            _ => payload.as_ptr(),
Ditto.

2022-10-17 07:11 UTC, mike1703 commented
changed the commit to use core directly and not the std reexport anymore

2022-10-17 08:21 UTC, ivmarkov commented
Thanks!

2022-10-17 08:21 UTC, merged