Add NVS usage example using the native Rust API
esp-rs/esp-idf-svc pull request #276
Opened 2023-07-18 17:21 UTC by punkto

Please note that I have added a new dependence (postcard) just for the example. I don't know if that is OK for you or it is better to use something already added (json?).

2023-07-22 06:35 UTC, ivmarkov commented
Dependencies which are only relevant for the `[examples]` section should be added in the `[dev-dependencies]` section.

2023-07-22 06:42 UTC, ivmarkov requested changes
Really just two small nits.

2023-07-22 06:42 UTC, ivmarkov commented on examples/nvs_get_set_raw_storage.rs
> +            Err(e) => info!("Couldn't get tag {} because{:?}", tag_raw_str, e),
Nit: missing space

2023-07-22 06:42 UTC, ivmarkov commented on examples/nvs_get_set_raw_storage.rs
> +    let tag_raw_u8 = "test_raw_u8";
Rather than `tag`s, can we name these things `key`s?

2023-07-22 06:42 UTC, ivmarkov commented on examples/nvs_get_set_raw_storage.rs
> +            Err(e) => info!("Couldn't get tag {} because{:?}", tag_raw_str, e),
Ditto - missing space?

2023-08-06 13:15 UTC, punkto commented
done!

2023-08-27 07:39 UTC, merged