Support home channel change
esp-rs/esp-idf-svc pull request #365
Opened 2024-02-16 10:24 UTC by MartinBroers

Commit to support WIFI_EVENT_HOME_CHANNEL_CHANGE, introduced in https://github.com/espressif/esp-idf/commit/1427e14b724292ee8ceede6523d98cdee7c06037. I have opted to 'just' support the event and not propagate the values which come into the struct in the C library, but I could add those if required.

Also, I guarded it with a config directive (`#[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]`, so not to break backwards builds. Maybe this is too restrictive, and we need to adjust for future builds (anything greater than 5.2), so  I am open to suggestions here. Or is the idea the next release works for 5.2 and not for older versions?

Also, I took the liberty to fix a few compilation errors and added 5.2 to the github workflow, but I am not sure this all is correct.

2024-02-17 11:35 UTC, ivmarkov requested changes
I think it is in a very good shape. However, if you could fix the `#cfg`s - see my other comments.

2024-02-17 11:35 UTC, ivmarkov commented on src/bt/a2dp.rs
> +        all(esp_idf_version_major = "5", esp_idf_version_minor = "0"),
Nit: simplify this by replacing with `all(esp_idf_version_major = "5", any(esp_idf_version_minor = "0", esp_idf_version_minor = "1"))`

2024-02-17 11:35 UTC, ivmarkov commented on src/bt/gap.rs
> +    all(esp_idf_version_major = "5", esp_idf_version_minor = "0"),
Ditto.

2024-02-17 11:35 UTC, ivmarkov commented on src/eth.rs
> +                    #[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]
This is not OK, as we'll have to touch it again once 5.3 or 6.0 is out. Rather, replace it with `not(<the upper condition>)`.

2024-02-17 11:35 UTC, ivmarkov commented on src/eth.rs
> +                    #[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]
Ditto.

2024-02-17 11:35 UTC, ivmarkov commented on src/eth.rs
> +                    #[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]
Ditto.

2024-02-17 11:35 UTC, ivmarkov commented on src/wifi.rs
> +            #[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]
Ditto - see above.

2024-02-17 11:35 UTC, ivmarkov commented on src/wifi.rs
> +#[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]
Ditto - see above.

2024-02-17 11:35 UTC, ivmarkov commented on src/wifi.rs
> +#[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]
Ditto - see above.

2024-02-17 11:35 UTC, ivmarkov commented on src/wifi.rs
> +#[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]
Ditto - see above.

2024-02-17 11:35 UTC, ivmarkov commented on src/wifi.rs
> +    #[cfg(all(esp_idf_version_major = "5", esp_idf_version_minor = "2",))]
Ditto - see above.

2024-02-17 12:43 UTC, MartinBroers commented
Thanks @ivmarkov , some good suggestions.

2024-02-19 12:31 UTC, MartinBroers commented
Updated MR to 
- Compile again. Something in rust-nightly has changed causing clippy errors. Fixed those in the last commit
- Not use BT in the sample sdkconfig, so we don't need the update on esp-idf-sys.

2024-02-19 13:05 UTC, ivmarkov requested changes

2024-02-19 13:05 UTC, ivmarkov commented on src/http/client.rs
> +#[cfg(not(feature = "default"))]
Should be `feature = "std"`, NOT `feature = "default"`.

2024-02-19 13:05 UTC, ivmarkov commented on src/http/server.rs
> +#[cfg(not(feature = "default"))]
Ditto.

2024-02-19 13:05 UTC, ivmarkov commented on src/mdns.rs
> +use alloc::{string::String, string::ToString, vec::Vec};
Ditto.

2024-02-19 13:05 UTC, ivmarkov commented on src/mqtt/client.rs
> +#[cfg(not(feature = "default"))]
Ditto

2024-02-19 13:05 UTC, ivmarkov commented on src/timer.rs
> +#[cfg(not(feature = "default"))]
Ditto

2024-02-19 13:05 UTC, ivmarkov commented on src/wifi.rs
> +#[cfg(not(feature = "default"))]
Ditto.

2024-02-19 13:05 UTC, ivmarkov commented on src/ws/client.rs
> +#[cfg(not(feature = "default"))]
Ditto.

2024-02-19 13:05 UTC, ivmarkov commented on .github/configs/sdkconfig.defaults
> +CONFIG_BT_ENABLED=n
Please restore the BT settings, but commented out, and put a short comment on top: "Uncomment to enable Classic BT"

2024-02-19 13:05 UTC, ivmarkov commented on src/espnow.rs
> +#[cfg(not(feature = "default"))]
See below.

2024-02-19 13:05 UTC, ivmarkov commented on src/eth.rs
> +#[cfg(not(feature = "default"))]
See below.

2024-02-19 13:05 UTC, ivmarkov commented on src/eventloop.rs
> +#[cfg(not(feature = "default"))]
See below.

2024-02-20 06:43 UTC, ivmarkov commented
@MartinBroers W.r.t. the clippy errors... I'm thinking we need a more generic fix. As in - for example - not importing the `std` prelude - ever - even if the `std` feature is enabled. Otherwise we need to sprincle the whole code with conditional imports, which is not nice at all.

2024-02-21 14:37 UTC, merged