Reflect changes in embedded-svc wifi ClientConfiguration
esp-rs/esp-idf-svc pull request #381
Opened 2024-03-06 22:52 UTC by embediver

Reflect the changes to `ClientConfiguration` in `embedded-svc` which will be introduced by https://github.com/esp-rs/embedded-svc/pull/75.

Before marking it ready, https://github.com/esp-rs/embedded-svc/pull/75 has to be merged and the dependency to `embedded-svc` has to be changed back in `Cargo.toml`.

2024-03-07 07:21 UTC, ivmarkov approved these changes
Looks OK. Once you are ready with both PRs (i.e. un-draft these), I'll merge. Just make sure to first fix the `embedded-svc` dependnency, so that we won't break the CI.

2024-03-07 07:21 UTC, ivmarkov commented on Cargo.toml
> +embedded-svc = { git = "https://github.com/embediver/embedded-svc.git", default-features = false }
Once this PR is ready for merge _and_ the corresponding one in `embedded-svc` is merged, we should restore the original dependency, and then put a `[patch.crates-io]` entry that points to the `embedded-svc` version from GIT.

2024-03-16 15:57 UTC, ivmarkov requested changes

2024-03-16 15:57 UTC, ivmarkov commented on Cargo.toml
> +[patch.crates-io]
I've merged the PR in `embedded-svc` now. Would you mind changing this to `https://github.com/esp-rs/embedded-svc.git`?

2024-03-16 16:12 UTC, ivmarkov commented
@embediver Sorry, just noticed that the CI fails - can you fix the failing example? Thanks!

2024-03-16 17:48 UTC, embediver commented
> @embediver Sorry, just noticed that the CI fails - can you fix the failing example? Thanks!

Sorry didn't notice that one example was feature-gated and forgot to check it.

But its fixed now.

2024-03-16 18:54 UTC, ivmarkov commented
Thanks!

2024-03-16 18:54 UTC, merged