clippy lints
esp-rs/esp-idf-svc pull request #410
Opened 2024-04-11 04:24 UTC by owenthewizard

Many many lints. Notably:
- Remove unneeded `Result` wrapping some function return types.
- `if ... { panic! }` to `assert!`
- Replaced `if let` with `map_or` and similar.
- [Make `fn` `const` if possible.](https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn)
- [`ptr::addr_of!` instead of `&T as *const T` ](https://rust-lang.github.io/rust-clippy/master/index.html#borrow_as_ptr)
- [`.cast() instead of `*const T as *const U`](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_as_ptr)
- [`.cast_mut()` instead of `*const T as *mut T`](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_cast_constness)
- [`U::from(T)` instead of `T as U`](https://rust-lang.github.io/rust-clippy/master/index.html#cast_lossless)
- `"{}". foo` -> `"{foo}"`
- [Use `Self`](https://rust-lang.github.io/rust-clippy/master/index.html#use_self)
- ...

As many of these are subjective, feel free to modify/request modifications.

2024-04-11 05:19 UTC, ivmarkov commented
> Many many lints. Notably:
> 
> * Remove unneeded `Result` wrapping some function return types.

I would accept this only for non-public API. Can you check and make sure you've done this change for private and crate-private methods only? If Clippy complains in public stuff, we should suppress its warnings there.

> * `if ... { panic! }` to `assert!`
> * Replaced `if let` with `map_or` and similar.
> * [Make `fn` `const` if possible.](https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn)
> * [`ptr::addr_of!` instead of `&T as *const T` ](https://rust-lang.github.io/rust-clippy/master/index.html#borrow_as_ptr)
> * [`.cast() instead of `*const T as *const U`](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_as_ptr)
> * [`.cast_mut()` instead of `*const T as *mut T`](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_cast_constness)
> * [`U::from(T)` instead of `T as U`](https://rust-lang.github.io/rust-clippy/master/index.html#cast_lossless)
> * `"{}". foo` -> `"{foo}"`
> * [Use `Self`](https://rust-lang.github.io/rust-clippy/master/index.html#use_self)
> * ...
> 
> As many of these are subjective, feel free to modify/request modifications.

The rest is fine. I don't have strong feelings for doing it one way or the other. These are stylistic changes and as you say, sometimes subjective.
As long as Clippy stays silent, I'm happy.

2024-04-11 05:25 UTC, ivmarkov commented
Actually one more thing: None of your improvements seem to address the actual clippy complaints which are currently failing the CI? All of the failures in the CI seem to be related to Clippy demanding that we use explicit turbofish typecasts when using `core::mem::transmute`. I think these should be addressed with priority.

2024-04-11 05:27 UTC, ivmarkov commented
And... your PR has come flicts. You need to rebase your PR on top of master. As in `git checkout <your-branch>`. Then `git pull`. Then `git rebase master --interactive`. ... and resolve all conflicts and upon resolving `git rebase --continue` until no conflicts are left and all your commits are on top of master.

2024-04-11 05:29 UTC, ivmarkov commented
... where `upstream/master` is the upstream master branch of esp-idf-svc. You can create the upstream remote repo with `git remote add https://github.com/esp-rs/esp-idf-svc`.

2024-04-11 05:33 UTC, ivmarkov commented
Ok conflicts seem to be fixed now, but clippy is still not happy. See the failing CI. I think given that this PR addresses Clippy lints, the CI should -as a minimum - be passing.

2024-04-11 15:04 UTC, owenthewizard commented on src/eth.rs
> -    ) -> Result<*mut esp_eth_phy_t, EspError> {
Removed uneeded `Result` (private API).

2024-04-11 15:06 UTC, owenthewizard commented on src/eth.rs
> -    pub unsafe fn set_nonstatic_rx_callback<F>(&mut self, callback: F) -> Result<(), EspError>
Same as above (public API).

2024-04-11 15:06 UTC, owenthewizard commented on src/eth.rs
> -    fn internal_set_rx_callback<F>(&mut self, callback: F) -> Result<(), EspError>
Private API, but needs to be changed to match public.

2024-04-11 15:10 UTC, owenthewizard commented on src/wifi.rs
> -    fn is_wps_finished(&self) -> Result<bool, EspError>;
Remove unneeded `Result` (private API).

2024-04-11 15:10 UTC, owenthewizard commented on src/wifi.rs
> -    fn is_wps_finished(&self) -> Result<bool, EspError> {
As above.

2024-04-11 15:11 UTC, owenthewizard commented on src/wifi.rs
> -    fn is_wps_finished(&self) -> Result<bool, EspError> {
As above.

2024-04-11 15:11 UTC, owenthewizard commented on src/wifi.rs
> -    pub fn is_wps_finished(&self) -> Result<bool, EspError> {
As above.

2024-04-11 15:12 UTC, owenthewizard commented on src/wifi.rs
> -    fn is_wps_finished(&self) -> Result<bool, EspError> {
As above.

2024-04-12 02:42 UTC, ivmarkov commented on src/eth.rs
> -    pub fn set_rx_callback<F>(&mut self, callback: F) -> Result<(), EspError>
Yes please.

2024-04-12 02:42 UTC, ivmarkov commented on src/eth.rs
> -    pub unsafe fn set_nonstatic_rx_callback<F>(&mut self, callback: F) -> Result<(), EspError>
Revert.

2024-04-12 04:16 UTC, ivmarkov requested changes
As mentioned, please revert the signatures of all public methods. The rest I'll accept and merge, though not sure what it gives us, as I think Clippy was only triggering on the `transmute` calls?

Last but not least and very important: I really do hope you've implemented these changes automatically with `cargo clippy --fix` or similar, as so.e of these are not so trivial, and if these were done manually, they could I trounce bugs, as I don't th8nk you've tested all changed code paths. Can you confirm that you've done these changes in an automatic fashion, and how exactly?

2024-04-12 11:21 UTC, owenthewizard commented
> Can you confirm that you've done these changes in an automatic fashion, and how exactly?

Unfortunately not as `clippy --fix` only works with a small subset of lints. Additionally it can't reason about `as *const _ as *mut _` -> `.cast().cast_mut()` without type hints. If you don't want to merge the changes due to this I completely understand. If you like I could submit multiple smaller PRs so the changes can be more easily reviewed.

Would you consider removing the unnecessary `Result` on the `EthDriver` callbacks in the next major/API update?

2024-04-12 11:28 UTC, ivmarkov commented
> > Can you confirm that you've done these changes in an automatic fashion, and how exactly?
> 
> Unfortunately not as `clippy --fix` only works with a small subset of lints. Additionally it can't reason about `as *const _ as *mut _` -> `.cast().cast_mut()` without type hints. If you don't want to merge the changes due to this I completely understand. If you like I could submit multiple smaller PRs so the changes can be more easily reviewed.

Splitting into multiple smaller PRs would help then. 

> Would you consider removing the unnecessary `Result` on the `EthDriver` callbacks in the next major/API update?

Not sure. Why do you need that so much?

2024-04-12 12:39 UTC, owenthewizard commented
> Not sure. Why do you need that so much?

I don't need it per se, I just think it's bloat since it always returns `Ok(())`.

2024-04-12 13:22 UTC, ivmarkov commented
> > Not sure. Why do you need that so much?
> 
> I don't need it per se, I just think it's bloat since it always returns `Ok(())`.

I think this is insignificant in the grant scheme of things. And it is not worth it to break backwards compatibility - even for a new API - because of this. Not to mention that in future we might need a result-returning API after all.

2024-04-12 13:34 UTC, owenthewizard commented
Closing this, will split into smaller PRs.

2024-04-12 13:34 UTC, closed without merging