ESP-IDF 5.2
esp-rs/esp-idf-svc pull request #416
Opened 2024-04-18 21:14 UTC by owenthewizard

ESP-IDF 5.2 adds a new field to the SPI ethernet configurations:

> Added option to use SPI Ethernet modules in poll mode without interrupt. [#12682](https://github.com/espressif/esp-idf/issues/12682) ([34ec96e](https://github.com/espressif/esp-idf/commit/34ec96ef23f701a9f72bb988b9195e959e97804d))

So far I have simply added the field and it passes `cargo check`, but there might be some further changes required?

2024-04-23 06:20 UTC, ivmarkov commented
CI fails though?

2024-04-23 06:22 UTC, ivmarkov requested changes

2024-04-24 19:01 UTC, owenthewizard commented
> CI fails though?

It seems to me this is because esp-idf-hal needs to be updated as well.

2024-04-25 05:09 UTC, ivmarkov commented
> > CI fails though?
> 
> It seems to me this is because esp-idf-hal needs to be updated as well.

No. The problem is in `eth.rs` and seems to come from your changes.

2024-04-25 16:56 UTC, owenthewizard commented
> > > CI fails though?
> > 
> > 
> > It seems to me this is because esp-idf-hal needs to be updated as well.
> 
> No. The problem is in `eth.rs` and seems to come from your changes.

I can't test the RISC-V targets:

```rust
error[E0463]: can't find crate for `core`
  |
  = note: the `riscv32imc-esp-espidf` target may not be installed
  = help: consider downloading the target with `rustup target add riscv32imc-esp-espidf`
```

2024-04-25 17:49 UTC, ivmarkov commented
>   = help: consider downloading the target with `rustup target add riscv32imc-esp-espidf`

Did you try what the compiler suggested?

2024-04-28 12:28 UTC, owenthewizard commented
> `rustup target add riscv32imc-esp-espidf`

Of course...

> error: toolchain 'esp' does not support components
> error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not support target 'riscv32imc-esp-espidf'

2024-04-28 12:54 UTC, ivmarkov commented
I think you are NOT really compiling with `cargo build -Zbuild-std ...`, as you should

Also can you do:
```sh
$ rustc --print target-list | grep espidf
```

It should print something like:
```
riscv32imac-esp-espidf
riscv32imafc-esp-espidf
riscv32imc-esp-espidf
```

2024-06-09 17:28 UTC, ivmarkov commented
This is now addressed in `master`.

2024-06-09 17:28 UTC, closed without merging