Safe wrapper for eth promiscuous mode
esp-rs/esp-idf-svc pull request #532
Opened 2024-12-23 23:09 UTC by indexds

Hello, this is my attempt at #246. This works locally, I could add wrappers for wifi as well for the sake of symmetry, though I have no use for them.

lmk

2024-12-24 11:51 UTC, ivmarkov requested changes

2024-12-24 11:51 UTC, ivmarkov commented on src/eth.rs
> +    pub fn set_promiscuous(&self, state: bool) -> Result<(), EspError> {
1. Put some documentation above the method. 
2. Do not take &self but &mut self.

2024-12-24 12:43 UTC, indexds commented
This should be fine I think. Want me to make a wrapper for wifi as well?

2024-12-26 07:42 UTC, merged

2024-12-26 13:18 UTC, ivmarkov commented
> This should be fine I think. Want me to make a wrapper for wifi as well?

If the Wifi driver actually does have such a mode and you could expose it that would be great.