Exposes core_id in the configuration of an HttpServer
esp-rs/esp-idf-svc pull request #534
Opened 2024-12-24 08:48 UTC by Angelo13C

2024-12-24 11:40 UTC, ivmarkov requested changes

2024-12-24 11:40 UTC, ivmarkov commented on src/http/server.rs
> +    pub core_id: i32,
`i32` is not ideal. Use [this](https://github.com/esp-rs/esp-idf-hal/blob/master/src/cpu.rs#L13) instead.

2024-12-24 11:54 UTC, ivmarkov commented
Also if you could also update the Changelog as the new PR template suggests? In section Breaking, as you are adding a new field to an existing struct which is not marked with non_exhaustive.

2025-01-02 23:49 UTC, indexds commented on CHANGELOG.md
> +- Add `core` field to `http::server::Configuration` to control which CPU core runs the HTTP server task
You're in the wrong place, 0.50.0 is already released, add a new ## [Unreleased] tag above

2025-01-02 23:53 UTC, indexds commented on src/http/server.rs
> +use esp_idf_hal::cpu::Core;
you'll want to do this instead since it's been re-exported in the crate
```rust
use crate::hal::cpu::Core; 
```

2025-01-02 23:55 UTC, indexds commented on src/http/server.rs
> +            core_id: conf.core.map(|core| core.into()).unwrap_or(i32::MAX),
This I'm not sure about because I don't know much about all this, but this should be a core still, no? Shouldn't you do something like this?

```rust
conf.core.map(|core| core.into()).unwrap_or(Core::Core0)
```
I'm not sure but it feels like i32::MAX would always crash.

2025-01-06 10:19 UTC, ivmarkov commented
This PR looks OK now, but merging it has to wait a bit, because adding a new field to the conf struct is backwards-incompatible (strictly speaking).

Fortunately, it is only a matter of a few days. Turns out, we need to release a new non-patch `esp-idf-svc` any way really soon, because of the new `embassy-time-driver` API which is also not backwards-compatible.

2025-01-12 18:13 UTC, indexds commented on src/http/server.rs
> +            core_id: conf.core.map(|core| core.into()).unwrap_or(i32::MAX),
Right, I checked, this is because of this definition

```c
#define tskNO_AFFINITY      ( ( BaseType_t ) 0x7FFFFFFF )
```

So probably add a comment that says i32::MAX is to say no core affinity?

2025-02-27 12:20 UTC, ivmarkov commented
It seems we are heading for another minor (= backwards-incompatible) release of `esp-idf-svc` so I would merge that.

Thanks!

2025-02-27 12:20 UTC, merged