Add source_ip function in EspHttpRawConnection
esp-rs/esp-idf-svc pull request #539
Opened 2024-12-28 00:51 UTC by indexds

## Thank you for your contribution!

We appreciate the time and effort you've put into this pull request.
To help us review it efficiently, please ensure you've gone through the following checklist:

### Submission Checklist 📝
- [x] I have updated existing examples or added new ones (if applicable).
- [x] I have used `cargo fmt` command to ensure that all changed code is formatted correctly.
- [x] I have used `cargo clippy` command to ensure that all changed code passes latest Clippy nightly lints.
- [x] My changes were added to the [`CHANGELOG.md`](https://github.com/esp-rs/esp-idf-svc/blob/main/esp-idf-svc/CHANGELOG.md) in the **_proper_** section.

### Pull Request Details 📖

#### Description
My attempt at #538. It works flawlessly on my end. 
#### Testing
```rust
    http_server.fn_handler("/", Method::Get, {
        move |mut request| {
            let html = "hello world";

            let connection = request.connection();

            log::info!("SOURCE IP: {}", connection.raw_connection()?.source_ip()?);

            connection.initiate_response(200, Some("OK"), &[("Content-Type", "text/html")])?;

            connection.write(html.as_bytes())?;

            Ok::<(), Error>(())
        }
    })?;
```

```
I (00:00:10.545) esp_netif_lwip: DHCP server assigned IP to a client, IP is: 192.168.100.2
I (00:00:12.947) charizhard::http: SOURCE IP: 192.168.100.2
```

2024-12-28 00:54 UTC, indexds commented
fixes #538

2024-12-28 00:59 UTC, indexds commented
Huh. Clippy doesn't complain on 5.2.3 but does on 5.1.2. What's going on here?

2024-12-28 15:49 UTC, indexds commented
```rust
mod c_char_definition {
    cfg_if! {
        // These are the targets on which c_char is unsigned.
        if #[cfg(any(
            all(
                target_os = "linux",
                any(
                    target_arch = "aarch64",
                    target_arch = "arm",
                    target_arch = "hexagon",
                    target_arch = "powerpc",
                    target_arch = "powerpc64",
                    target_arch = "s390x",
                    target_arch = "riscv64",
                    target_arch = "riscv32",
                    target_arch = "csky"
                )
            ),
            all(target_os = "android", any(target_arch = "aarch64", target_arch = "arm")),
            all(target_os = "l4re", target_arch = "x86_64"),
            all(
                any(target_os = "freebsd", target_os = "openbsd"),
                any(
                    target_arch = "aarch64",
                    target_arch = "arm",
                    target_arch = "powerpc",
                    target_arch = "powerpc64",
                    target_arch = "riscv64"
                )
            ),
            all(
                target_os = "netbsd",
                any(
                    target_arch = "aarch64",
                    target_arch = "arm",
                    target_arch = "powerpc",
                    target_arch = "riscv64"
                )
            ),
            all(
                target_os = "vxworks",
                any(
                    target_arch = "aarch64",
                    target_arch = "arm",
                    target_arch = "powerpc64",
                    target_arch = "powerpc"
                )
            ),
            all(
                target_os = "fuchsia",
                any(target_arch = "aarch64", target_arch = "riscv64")
            ),
            all(target_os = "nto", target_arch = "aarch64"),
            target_os = "horizon",
            target_os = "aix",
        ))] {
            pub type c_char = u8;
        } else {
            // On every other target, c_char is signed.
            pub type c_char = i8;
        }
    }
}
```
So i'm pretty sure this is what's causing the problem. Do I just paste that cfg in the offending places? That's gonna be ugly

2025-01-01 08:34 UTC, ivmarkov requested changes

2025-01-01 08:34 UTC, ivmarkov commented on src/http/server.rs
> +                return Err(EspError::from(-1).unwrap());
Here and everywhere below you rather want:
```rust
return Err(EspError::from_infallible::<ESP_FAIL>());
```

or just
```rust
Err(EspError::from_infallible::<ESP_FAIL>())?;
```

2025-01-01 08:34 UTC, ivmarkov commented on src/http/server.rs
> +            //"255.255.255.255\0" = 16 bytes
The whole `sin_addr`-to-char-then-to-`Ipv4Addr` equilibristic is unnecessary.

`sin_addr.s_addr` is of type `uint32_t` = `u32` and represents the Ipv4 address either in big or little endian (can't remember which one it was) but you can easily figure it out.

If you need to get the bytes of it, either do `sin_addr.s_addr.,to_le_bytes()` ot `sin_addr.s_addr.to_be_bytes()`.

2025-01-01 08:34 UTC, ivmarkov commented on src/http/server.rs
> +            let mut ip_string: [ffi::c_char; 40] = [0; 40];
Ditto here. Convert the [`in6_addr`](https://learn.microsoft.com/en-us/windows/win32/api/in6addr/ns-in6addr-in6_addr) struct directly, by using either the bytes or the 16-bit segments union to `Ipv6Addr`.

2025-01-01 13:19 UTC, indexds commented
UUuuuh everything just broke locally and on the CI, what's going on with the sys crate?

```
rror[E0433]: failed to resolve: use of undeclared crate or module `bindgen`
   --> C:\Program Files\Rust\.cargo\git\checkouts\esp-idf-sys-d4c2e811b42d99d6\e2795ac\build/build.rs:101:39
    |
101 |     let configure_bindgen = |bindgen: bindgen::Builder| {  
    |                                       ^^^^^^^ use of undeclared crate or module `bindgen`
    |
help: consider importing one of these modules
    |
1   + use crate::bindgen_utils::bindgen;
    |
1   + use embuild::bindgen::bindgen;
    |

warning: unused import: `embuild::bindgen::BindgenExt`
 --> C:\Program Files\Rust\.cargo\git\checkouts\esp-idf-sys-d4c2e811b42d99d6\e2795ac\build/build.rs:6:5
  |
6 | use embuild::bindgen::BindgenExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0433`.
warning: `esp-idf-sys` (build script) generated 1 warning
error: could not compile `esp-idf-sys` (build script) due to 1 previous error; 1 warning emitted

```

2025-01-01 13:20 UTC, indexds commented
Ah, you broke it I  think

https://github.com/esp-rs/esp-idf-sys/commit/e2795acc52dc86d0d33308526f36ca15f01593dc

2025-01-01 13:53 UTC, ivmarkov commented
> Ah, you broke it I think
> 
> [esp-rs/esp-idf-sys@e2795ac](https://github.com/esp-rs/esp-idf-sys/commit/e2795acc52dc86d0d33308526f36ca15f01593dc)

Should be OK now.

2025-01-01 14:31 UTC, indexds commented
Is there an easy way to make an empty commit that forces the CI to re-run?

2025-01-01 14:57 UTC, ivmarkov commented
> Is there an easy way to make an empty commit that forces the CI to re-run?

I'll just bite the bullet and merge as-is. If it breaks the build, I'll fix, no worries.

2025-01-01 14:57 UTC, merged