Websocket implementation
esp-rs/esp-idf-svc pull request #69
Opened 2022-04-29 08:54 UTC by Witcher01

following the esp_websocket_client found here[^1][^2], this commit
wraps the mentioned C library in Rust to expose a safe WebSocket
interface.
The exposed API copies the previously implemented MQTT API. On creating
a `EspWebSocketClientConfig` and passing it to a `EspWebSocketClient`,
the user can call `send` to send data. Manual sending of fragmented data,
Ping/Pong, or Connect/Disconnect are not supported due to the underlying
C library not supporting this, either.
Receiving is done in a new thread with the returned
`EspWebSocketConnection` and its blocking `next` function call, which
wakes on receiving one of the events defined in `WebSocketEventType`.
The `EspWebSocketClient` takes a `time::Duration` timeout since the
underlying C lib requires this but the defined interface in the
`embedded_svc` create does not provide it as a parameter.
On dropping the `EspWebSocketClient` the C functions
`esp_websocket_client_close` and `esp_websocket_client_destroy` are
being called, cleanly closing the connection to the WebSocket server.

[^1]: https://espressif.github.io/esp-protocols/esp_websocket_client/
[^2]: https://github.com/espressif/esp-protocols/

This requires esp-rs/esp-idf-sys/pull/88.

2022-04-30 20:16 UTC, ivmarkov commented
Can you look at the build output. It fails not just with clippy, but also with real compilation errors?

2022-05-01 15:56 UTC, ivmarkov commented
> Can you look at the build output. It fails not just with clippy, but also with real compilation errors?

Sorry, my mistake. I need to first merge the changes to `esp-idf-sys`.

2022-05-04 09:20 UTC, Witcher01 commented
@ivmarkov build failed due to `ws` being specified as an `experimental` feature in `embedded-svc`.
More errors follow after fixing this, which don't happen on the fork I develop on locally, but which can be reproduced when cloning cleanly. I'll investigate.

2022-05-04 10:48 UTC, ivmarkov commented
Ease change the PR so that the experimental feature is temporarily enabled.

2022-05-04 15:44 UTC, ivmarkov commented
You need to rebase your fork on top of latest esp-idf-svc master to resolve the conflicts.

2022-05-05 15:41 UTC, Witcher01 commented
@ivmarkov There are some warnings left in `src/eth.rs` which I suspect will prevent the `Build | Clippy` step in the CI from passing due to warnings being treated as errors.
Should I fix these, too?

2022-05-05 18:37 UTC, ivmarkov commented
No it's OK like that. The eth related warnings seem to be for other architecture (xtens). Please keep in mind that my review will be delayed as I would be traveling tmr and over the weekend

2022-05-13 06:27 UTC, ivmarkov requested changes

2022-05-13 06:27 UTC, ivmarkov commented on src/ws/client.rs
> +    pub fn new(
Rename to `new_with_connection` to match the latest mqtt API

2022-05-13 06:27 UTC, ivmarkov commented on src/ws/client.rs
> +    fn new_with_raw_callback(
Rename to just `new`.

2022-05-13 06:27 UTC, ivmarkov commented on src/ws/client.rs
> +                panic!("Unsupported operation: Sending of fragmented data!")
Perhaps remove the `!` from all messages?

2022-05-13 08:41 UTC, Witcher01 commented on src/ws/client.rs
> +    pub fn next(&mut self) -> Option<anyhow::Result<WebSocketEvent>> {
I'm not sure either, all I can say is that it does compile 😅 Should I change it to what you expected?

2022-05-13 08:43 UTC, Witcher01 commented on src/ws/client.rs
> +    pub task_stack: u8,
I'm assuming you mean both `task_prio` and `task_stack` and I should cast it down to `u8` in the `try_from`?
Is that fine? The C lib requires a `u8`, but with a `usize` we're signalling that both variables can hold bigger values.

2022-05-13 09:15 UTC, Witcher01 commented on src/ws/client.rs
> +            esp_websocket_event_id_t_WEBSOCKET_EVENT_MAX => {
I think you're right, I'm taking it out.

2022-05-13 09:28 UTC, Witcher01 commented on src/ws/client.rs
> +    pub uri: Option<&'a str>,
I'm not sure what you mean with the last point. Should I just remove `username` and `password` from the config struct altogether?

2022-05-16 08:19 UTC, merged